### ISSUE TITLE
CDC 2.5 and 3.2 profiles - universe

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#103]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

Add information on Universe. It is important for researchers to know what the universe has been. Specifications should inlude both ‘including’ and ‘excluding’ information of Universe.

Should be ‘Optional’.

DDI-L

ddi:DDIInstance/s:StudyUnit/c:ConceptualComponent/c:UniverseScheme/c:Universe/r:Description/r:Content \(Optional\) \(0-n\)

Inclusion and exclusion by “isInclusive” \(value “true” or if is exclusive, then “false”\), if I understood correctly. For instance, if the universe in the national population but excluding individuals living in institutions.

‌

**Comment by darrenbell2** [comment]
Added following to 2.5 profile (also updated 2.5_mono and 1.2.2. and 1.2.2_mono with appropriate adaptations):

    
    
    
    <pr:Used xpath="/codeBook/stdyDscr/stdyInfo/sumDscr/universe" isRequired="false">
        <r:Description>
            <r:Content>Required: Recommended</r:Content>
            <r:Content>ElementType: Content element</r:Content>
            <r:Content>ElementRepeatable: Yes</r:Content>
            <r:Content>Usage: Description of population or other elements studied or measured (freetext).</r:Content>
            <r:Content>CDC_UI_Label: None</r:Content>
            <r:Content>CMM_Mapping: 1.3.4</r:Content>
        </r:Description>
        <pr:Instructions>
            <r:Content><![CDATA[
			<Constraints>
				<RecommendedNodeConstraint/>
			</Constraints>
			]]></r:Content>
        </pr:Instructions>
    </pr:Used>
    <pr:Used xpath="/codeBook/stdyDscr/stdyInfo/sumDscr/universe/@xml:lang" isRequired="false">
        <r:Description>
            <r:Content>Required: Mandatory if 'universe' element is present.</r:Content>
            <r:Content>ElementType: Attribute</r:Content>
            <r:Content>Usage: Language of the Universe item. ISO 639-1 codes are strongly
                encouraged to be used.</r:Content>
            <r:Content>CDC_UI_Label: None</r:Content>
            <r:Content>CMM_Mapping: 1.3.4.1</r:Content>
        </r:Description>
        <pr:Instructions>
            <r:Content>
                <![CDATA[
                <Constraints>
                    <MandatoryNodeIfParentPresentConstraint/>
                </Constraints>
                ]]>
            </r:Content>
        </pr:Instructions>
    </pr:Used>
    <pr:Used xpath="/codeBook/stdyDscr/stdyInfo/sumDscr/universe/@clusion" isRequired="false">
        <r:Description>
            <r:Content>Required: Optional</r:Content>
            <r:Content>ElementType: Attribute</r:Content>
            <r:Content>Usage: The default value is "true" in DDI-L. The description statement of a 
                universe is generally stated in inclusive terms such as "All persons residing in Europe". 
                Occasionally a universe is defined by what it excludes, i.e., "All persons residing 
                in Europe except for those residing on U.S. Military bases". 
                In this case the value would be changed to "false". 
                In DDI-C, attribute clusion states the inclusion/exclusion with values "I" and "E" respectively.</r:Content>
            <r:Content>CDC_UI_Label: None</r:Content>
            <r:Content>CMM_Mapping: 1.3.4.2</r:Content>
        </r:Description>
        <pr:Instructions>
            <r:Content><![CDATA[
			<Constraints>
				<OptionalNodeConstraint/>
			</Constraints>
			]]></r:Content>
        </pr:Instructions>
    </pr:Used>

**Comment by darrenbell2** [comment]
Added following to 3.2 profile:

    
    
    
    <pr:Used xpath="/ddi:DDIInstance/s:StudyUnit/c:ConceptualComponent/c:UniverseScheme/c:Universe/r:Description/r:Content" isRequired="false">
        <r:Description>
            <r:Content>Required: Recommended</r:Content>
            <r:Content>ElementType: Content element</r:Content>
            <r:Content>ElementRepeatable: Yes</r:Content>
            <r:Content>Usage: Description of population or other elements studied or measured (freetext).</r:Content>
            <r:Content>CDC_UI_Label: None</r:Content>
            <r:Content>CMM_Mapping: 1.3.4</r:Content>
        </r:Description>
        <pr:Instructions>
            <r:Content><![CDATA[
			<Constraints>
				<RecommendedNodeConstraint/>
			</Constraints>
			]]></r:Content>
        </pr:Instructions>
    </pr:Used>
    <pr:Used xpath="/ddi:DDIInstance/s:StudyUnit/c:ConceptualComponent/c:UniverseScheme/c:Universe/r:Description/r:Content/@xml:lang" isRequired="false">
        <r:Description>
            <r:Content>Required: Mandatory if '../c:Universe/r:Description/r:Content' element is present.</r:Content>
            <r:Content>ElementType: Attribute</r:Content>
            <r:Content>Usage: Language of the Universe item. ISO 639-1 codes are strongly
                encouraged to be used.</r:Content>
            <r:Content>CDC_UI_Label: None</r:Content>
            <r:Content>CMM_Mapping: 1.3.4.1</r:Content>
        </r:Description>
        <pr:Instructions>
            <r:Content>
                <![CDATA[
                <Constraints>
                    <MandatoryNodeIfParentPresentConstraint/>
                </Constraints>
                ]]>
            </r:Content>
        </pr:Instructions>
    </pr:Used>
    <pr:Used xpath="/ddi:DDIInstance/s:StudyUnit/c:ConceptualComponent/c:UniverseScheme/c:Universe/@isInclusive" isRequired="false">
        <r:Description>
            <r:Content>Required: Optional</r:Content>
            <r:Content>ElementType: Attribute</r:Content>
            <r:Content>Usage: The default value is "true" in DDI-L. The description statement of a 
                universe is generally stated in inclusive terms such as "All persons residing in Europe". 
                Occasionally a universe is defined by what it excludes, i.e., "All persons residing 
                in Europe except for those residing on U.S. Military bases". 
                In this case the value would be changed to "false". 
                In DDI-C, attribute clusion states the inclusion/exclusion with values "I" and "E" respectively.</r:Content>
            <r:Content>CDC_UI_Label: None</r:Content>
            <r:Content>CMM_Mapping: 1.3.4.2</r:Content>
        </r:Description>
        <pr:Instructions>
            <r:Content><![CDATA[
			<Constraints>
				<OptionalNodeConstraint/>
			</Constraints>
			]]></r:Content>
        </pr:Instructions>
    </pr:Used>

**Comment by matthew-morris-cessda** [comment]
Reopening, as this hasn't been merged into main (or mdo-d6)
