### ISSUE TITLE
CDC 2.5 and 3.2 profiles: access CV information

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#104]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

CESSDA will have an access vocabulary to which SPs will map their access categories. This will allow CDC users to narrow down their searches to open access data.

So far neither DDI-C nor DDI-L have an element for this but Darren had an idea of how this information could be incorporated into the profiles. Important to have. 

* Having truly open data \(just download\) double data downloads at FSD, so users really are looking for open access data.

CV Element promised for DDI 2.6.

**Comment by darrenbell2** [comment]
Implemented following in 2.5, 2.5_mono, 1.2.2 and 1.2.2_mono profiles:
    
    
    
    <pr:Used xpath="/codeBook/stdyDscr/dataAccs/useStmt/conditions" isRequired="true">
        <r:Description>
            <r:Content>Required: Mandatory</r:Content>
            <r:Content>ElementType: Content element</r:Content>
            <r:Content>ElementRepeatable: Yes</r:Content>
            <r:Content>Usage: Controlled description of the data access (open access vs. restricted access).
                CDC will use the same Access Rights vocabulary as OpenAIRE. 
                The name of the vocabulary is “info:eu-repo-Access-Terms vocabulary” - see
                http://purl.org/eu-repo/semantics/#info-eu-repo-AccessRights
                Only the codes “restrictedAccess” and “openAccess” will be used.</r:Content>
            <r:Content>CDC_UI_Label: Open/Closed</r:Content>
            <r:Content>CMM_Mapping: 1.4.1</r:Content>
        </r:Description>
    </pr:Used>
    <pr:Used xpath="/codeBook/stdyDscr/dataAccs/useStmt/conditions/@elementVersion" 
        defaultValue="info:eu-repo-Access-Terms vocabulary" fixedValue="true" isRequired="false">
        <r:Description>
            <r:Content>Required: Mandatory if 'conditions' element is present</r:Content>
            <r:Content>ElementType: Attribute</r:Content>
            <r:Content>Usage: Always 'info:eu-repo-Access-Terms vocabulary'.</r:Content>
            <r:Content>CMM_Mapping: 1.4.1</r:Content>
        </r:Description>
        <pr:Instructions>
            <r:Content>
                <![CDATA[
                <Constraints>
                    <MandatoryNodeIfParentPresentConstraint/>
                </Constraints>
                ]]>
            </r:Content>
        </pr:Instructions>
    </pr:Used>

**Comment by darrenbell2** [comment]
Implemented following in CDC 3.2 profile:
    
    
    
    <pr:Used xpath="/ddi:DDIInstance/s:StudyUnit/a:Archive/a:ArchiveSpecific/a:Item/a:Access/a:AccessTypeName/r:String" isRequired="true">
        <r:Description>
            <r:Content>Required: Mandatory</r:Content>
            <r:Content>ElementType: Content element</r:Content>
            <r:Content>ElementRepeatable: Yes</r:Content>
            <r:Content>Usage: Controlled description of the data access (open access vs. restricted access).
                CDC will use the same Access Rights vocabulary as OpenAIRE. 
                The name of the vocabulary is “info:eu-repo-Access-Terms vocabulary” - see
                http://purl.org/eu-repo/semantics/#info-eu-repo-AccessRights
                Only the codes “restrictedAccess” and “openAccess” will be used.</r:Content>
            <r:Content>CDC_UI_Label: Open/Closed</r:Content>
            <r:Content>CMM_Mapping: 1.4.1</r:Content>
        </r:Description>
    </pr:Used>
    <pr:Used xpath="ddi:DDIInstance/s:StudyUnit/a:Archive/a:ArchiveSpecific/a:Item/a:Access/a:AccessTypeName/@‌context" 
        defaultValue="info:eu-repo-Access-Terms vocabulary" fixedValue="true" isRequired="false">
        <r:Description>
            <r:Content>Required: Mandatory if '../a:AccessTypeName' element is present</r:Content>
            <r:Content>ElementType: Attribute</r:Content>
            <r:Content>Usage: Always 'info:eu-repo-Access-Terms vocabulary'.</r:Content>
            <r:Content>CMM_Mapping: 1.4.1</r:Content>
        </r:Description>
        <pr:Instructions>
            <r:Content>
                <![CDATA[
                <Constraints>
                    <MandatoryNodeIfParentPresentConstraint/>
                </Constraints>
                ]]>
            </r:Content>
        </pr:Instructions>
    </pr:Used>

**Comment by darrenbell2** [comment]
Will close as new 2.6 and 3.3. profiles will be based in 2.5/3.2 and hence will incorporate this information.

**Comment by matthew-morris-cessda** [comment]
Reopening, as this hasn't been merged into main (or mdo-d6)
