### ISSUE TITLE
EQB2.5: /codeBook/docDscr/citation/holdings/@URI needed?

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#108]
**Original report on BitBucket by Darren Bell (GitHub: [darrenbell2](https://github.com/darrenbell2)).**

----------------------------------------

Source: FSD EQB2.5 Profile Feedback 30-Nov-2021  
[https://github.com/cessda/cessda.metadata.profiles/issues/105](https://github.com/cessda/cessda.metadata.profiles/issues/105)

Is this something that EQB generates? This usually has the information of the SP \(Publisher\)?

**Comment by katja-moilanen** [comment]
https://github.com/cessda/cessda.metadata.profiles/issues/113
