### ISSUE TITLE
CDC 3.2 Publication information

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#109]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

Copying the suggested x-paths from the CDC Upgrade report x-paths:

Related publication

* ddi:DDIInstance/s:StudyUnit/r:OtherMaterialScheme/r:OtherMaterial/

\+

* ddi:DDIInstance/s:StudyUnit/r:OtherMaterialScheme/r:OtherMaterial/r:TypeOfMaterial = “related publication”

‌

Title of the publication

ddi:DDIInstance/s:StudyUnit/r:OtherMaterialScheme/r:OtherMaterial/r:Citation/r:Title/r:String

* Recommended as not mandatory in DDI3. Here the CDC DDI-C and DDI-L profiles differ as the element is mandatory in DDI2 \(but should not be\).

‌

ID

ddi:DDIInstance/s:StudyUnit/r:OtherMaterialScheme/r:OtherMaterial/r:Citation/r:InternationalIdentifier/r:IdentifierContent

‌

Agency

ddi:DDIInstance/s:StudyUnit/r:OtherMaterialScheme/r:OtherMaterial/r:Citation/r:InternationalIdentifier/r:ManagingAgency

‌

@MortenSikt @&zwnj;Hilde Orten Please review. For Usage information, see related issue for DDI-C profile #66.

‌

**Comment by darrenbell2** [comment]
Hi @MortenSikt  - publications info is now not mandatory in the 2.5 profile - see below, so I will close this now.  However, please re-open if I have misunderstood.   Thanks, Darren

    
    
    
    <pr:Used xpath="/codeBook/stdyDscr/othrStdyMat/relPubl/citation/titlStmt/IDNo"
        isRequired="false">
        <r:Description>
            <r:Content>Required: Recommended</r:Content>
            <r:Content>ElementType: Content element</r:Content>
            <r:Content>ElementRepeatable: Yes</r:Content>
            <r:Content>Usage: PID of the publication. Required by OpenAire to to relate the
                publication to a dataset.</r:Content>
            <r:Content>CMM_Mapping: 9.9</r:Content>
        </r:Description>
        <pr:Instructions>
            <r:Content><![CDATA[
			<Constraints>
				<OptionalNodeConstraint/>
			</Constraints>
			]]></r:Content>
        </pr:Instructions>
    </pr:Used>
    <pr:Used xpath="/codeBook/stdyDscr/othrStdyMat/relPubl/citation/titlStmt/IDNo/@agency"
        isRequired="false">
        <r:Description>
            <r:Content>Required: Mandatory if '..../IDNo' element is present.</r:Content>
            <r:Content>ElementType: Attribute</r:Content>
            <r:Content>Usage: Agency responsible for the identifier of the publication. Required by
                OpenAire and the value has to come from their controlled list of
                relatedIdentifierTypes:
                https://guidelines.openaire.eu/en/latest/data/field_relatedidentifier.html#d-relatedidentifier..</r:Content>
            <r:Content>CMM_Mapping: 9.9.1</r:Content>
        </r:Description>
        <pr:Instructions>
            <r:Content>
                <![CDATA[
                <Constraints>
                    <MandatoryNodeIfParentPresentConstraint/>
                </Constraints>
                ]]>
            </r:Content>
        </pr:Instructions>
    </pr:Used>
    <pr:Used xpath="/codeBook/stdyDscr/othrStdyMat/relPubl/citation/holdings/@URI"
        isRequired="false">
        <r:Description>
            <r:Content>Required: Recommended.</r:Content>
            <r:Content>ElementType: Attribute</r:Content>
            <r:Content>Usage: URL of website on which the publication can be found (or at least information concerning 
                the literature).</r:Content>
            <r:Content>CMM_Mapping: 9.10</r:Content>
        </r:Description>
        <pr:Instructions>
            <r:Content><![CDATA[
			<Constraints>
				<RecommendedNodeConstraint/>
			</Constraints>
			]]></r:Content>
        </pr:Instructions>
    </pr:Used>

**Comment by MortenSikt** [comment]
It is correct that this should not be mandatory. Only possible issue here might be when sending records to OpenAire with related publications where PID is not present due to the fact that it does not exist for the publication. But that can be handled elsewhere.

**Comment by katja-moilanen** [comment]
Done in the year 2023
