### ISSUE TITLE
CDC all profiles: amend CESSDA Topic Classification vocabURI

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#110]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

Amend the vocabURI information of Topic Classification in all CDC profiles.

The correct URI is: [https://vocabularies.cessda.eu/urn/urn:ddi:int.cessda.cv:TopicClassification:](https://vocabularies.cessda.eu/vocabulary/TopicClassification)\[version number\]

‌

For DDI 2.5, for example: 

</codeBook/stdyDscr/stdyInfo/subject/topcClas/@&zwnj;vocabURI" isRequired="false">  
…

<r:Content>  
Usage: Use the URI of the CV version that is being used. For example, for version 4.2 of CESSDA Topic Classification. use:  [https://vocabularies.cessda.eu/urn/urn:ddi:int.cessda.cv:TopicClassification:4.2](https://vocabularies.cessda.eu/vocabulary/TopicClassification)  
</r:Content>

….

**Comment by darrenbell2** [comment]
Usage note updated in CDC 1.2.2, 2.5, 3.2 profiles like so:

            <r:Content>Usage: Use the URI of the CV version that is being used based on the pattern 
                "https://vocabularies.cessda.eu/urn/urn:ddi:int.cessda.cv:TopicClassification:[version number]"
                For example, for version 4.2 of CESSDA Topic Classification, use
                "https://vocabularies.cessda.eu/urn/urn:ddi:int.cessda.cv:TopicClassification:4.2"</r:Content>

**Comment by darrenbell2** [comment]
Committed to mdo-d6 branch

**Comment by matthew-morris-cessda** [comment]
Reopening, as this hasn't been merged into main (or mdo-d6)
