### ISSUE TITLE
DDI vocabularies http resolver

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#111]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

Thinking about the ‘vocabURI’ of DDI vocabularies in profiles.

Looking at [https://registry.ddialliance.org/](https://registry.ddialliance.org/), there does not seem to be http resolver available so I do not know what should be put in front of the vocabulary urn to get a permanent http address for a CV version.

Something like

[http://\[resolver\]/urn/urn:ddi:int.ddi.cv:AnalysisUnit:2.1](http://[resolver]/urn/urn:ddi:int.ddi.cv:AnalysisUnit:2.1)

But as I’m not a tech person, might have misunderstood something.

**Comment by katja-moilanen** [comment]
This seems to be an issue for CVS, not DDI profiles?

**Comment by katja-moilanen** [comment]
This is seems to be an old CVS issue.
