### ISSUE TITLE
EQB 2.5 Profile: use of othrStdyMat versus otherMat

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#121]
**Original report on BitBucket by Darren Bell (GitHub: [darrenbell2](https://github.com/darrenbell2)).**

----------------------------------------

Element otherMat may be used: it has citation and its child elements too

_Related to usage of  4 elements/attributes:_

1. _EQB 2.5 Profile: /codeBook/stdyDscr/othrStdyMat/relMat/citation/titlStmt/titl_
2. _EQB 2.5 Profile: /codeBook/stdyDscr/othrStdyMat/relMat/citation/titlStmt/titl/@&zwnj;xml:lang_
3. _EQB 2.5 Profile: /codeBook/stdyDscr/othrStdyMat/relMat/citation/titlStmt/partitl_
4. _EQB 2.5 Profile: /codeBook/stdyDscr/othrStdyMat/relMat/citation/titlStmt/parTitl/@&zwnj;xml:lang_

---

Source of comment:  
From: Katja Moilanen \(Basecamp\) [*email address removed*](mailto:*email address removed*)  
Sent: 30 November 2021 11:41  
To: Bell, Darren S [*email address removed*](mailto:*email address removed*)  
Subject: Re: \(CESSDA Metadata Office\) Your feedback on the new DDI profile drafts \(CDC and EQB\) is needed!  
please find attached to this message the FSD's feedback on the EQB DDI 2.5 profile.  It includes general comments about the profile as well as information about FSD's capability to produce "EQB valid" DDI 2.5 metadata.  
Best wishes,  
Katja

‌

**Comment by katja-moilanen** [comment]
Issue not relevant any longer?

This field is not part of the EQB plans. Might need to be removed from the profile.

**Comment by katja-moilanen** [comment]
This issues concerns old, deprecated EQB 2.5 profile.
