### ISSUE TITLE
EQB 2.5 Profile: /codeBook/dataDscr/var/location/@width

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#127]
**Original report on BitBucket by Darren Bell (GitHub: [darrenbell2](https://github.com/darrenbell2)).**

----------------------------------------

According to DDI-C specification, this element \+ attribute is not about the minimum length of the text variable, instead it is meant to assist in reading the variable from the file to a \(statistical\) programme. [https://ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/field\_level\_documentation\_files/schemas/codebook\_xsd/elements/location.html](https://ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/field_level_documentation_files/schemas/codebook_xsd/elements/location.html)

‌

Source of comment:  
From: Katja Moilanen \(Basecamp\) [*email address removed*](mailto:*email address removed*)  
Sent: 30 November 2021 11:41  
To: Bell, Darren S [*email address removed*](mailto:*email address removed*)  
Subject: Re: \(CESSDA Metadata Office\) Your feedback on the new DDI profile drafts \(CDC and EQB\) is needed!  
please find attached to this message the FSD's feedback on the EQB DDI 2.5 profile.  It includes general comments about the profile as well as information about FSD's capability to produce "EQB valid" DDI 2.5 metadata.  
Best wishes,  
Katja

**Comment by katja-moilanen** [comment]
This field is not part of the EQB plans. Might need to be removed from the profile.

**Comment by katja-moilanen** [comment]
https://github.com/cessda/cessda.metadata.profiles/issues/86
