### ISSUE TITLE
EQB 2.5 Profile: /codeBook/dataDscr/var/qstn/@seqNo

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#128]
**Original report on BitBucket by Darren Bell (GitHub: [darrenbell2](https://github.com/darrenbell2)).**

----------------------------------------

Missing the //var/qstn and if it is M, R or O.

Is any SP using this?

There is also another Question number element in this profile: /codeBook/dataDscr/var/qstn/list/itm . Is it necessary to have 2 of them? This one is better?

---

Source of comment:  
From: Katja Moilanen \(Basecamp\) [*email address removed*](mailto:*email address removed*)  
Sent: 30 November 2021 11:41  
To: Bell, Darren S [*email address removed*](mailto:*email address removed*)  
Subject: Re: \(CESSDA Metadata Office\) Your feedback on the new DDI profile drafts \(CDC and EQB\) is needed!  
please find attached to this message the FSD's feedback on the EQB DDI 2.5 profile.  It includes general comments about the profile as well as information about FSD's capability to produce "EQB valid" DDI 2.5 metadata.  
Best wishes,  
Katja

**Comment by katja-moilanen** [comment]
This field is not part of the EQB plans. Might need to be removed from the profile.

**Comment by katja-moilanen** [comment]
https://github.com/cessda/cessda.metadata.profiles/issues/91
