### ISSUE TITLE
EQB 2.5 Profile: /codeBook/dataDscr/var/catgryGrp/@levelnm [delete]

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#138]
**Original report on BitBucket by Darren Bell (GitHub: [darrenbell2](https://github.com/darrenbell2)).**

----------------------------------------

Is catgryGrp element M, R, O?

Is any SP using this?

---

Source of comment:  
From: Katja Moilanen \(Basecamp\) [*email address removed*](mailto:*email address removed*)  
Sent: 30 November 2021 11:41  
To: Bell, Darren S [*email address removed*](mailto:*email address removed*)  
Subject: Re: \(CESSDA Metadata Office\) Your feedback on the new DDI profile drafts \(CDC and EQB\) is needed!  
please find attached to this message the FSD's feedback on the EQB DDI 2.5 profile.  It includes general comments about the profile as well as information about FSD's capability to produce "EQB valid" DDI 2.5 metadata.  
Best wishes,  
Katja

**Comment by katja-moilanen** [comment]
catgryGrp is not meant to be used for describing code lists in this way

**Comment by katja-moilanen** [comment]
This issues concerns old, deprecated EQB 2.5 profile.
