### ISSUE TITLE
EQB 2.5 Profile: /codeBook/dataDscr/var/concept/list/itm/label and ../item/p

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#144]
**Original report on BitBucket by Darren Bell (GitHub: [darrenbell2](https://github.com/darrenbell2)).**

----------------------------------------

Using //concept/list/itm/label \(and //concept/list/itm/p\) is not a perfect way to document this, but quite likely there is no better way to document this information with DDI-C.

---

Source of comment:  
From: Katja Moilanen \(Basecamp\) [*email address removed*](mailto:*email address removed*)  
Sent: 30 November 2021 11:41  
To: Bell, Darren S [*email address removed*](mailto:*email address removed*)  
Subject: Re: \(CESSDA Metadata Office\) Your feedback on the new DDI profile drafts \(CDC and EQB\) is needed!  
please find attached to this message the FSD's feedback on the EQB DDI 2.5 profile. It includes general comments about the profile as well as information about FSD's capability to produce "EQB valid" DDI 2.5 metadata.  
Best wishes,  
Katja

**Comment by katja-moilanen** [comment]
Could the label be put directly into concept element?

**Comment by katja-moilanen** [comment]
This issues concerns old, deprecated EQB 2.5 profile.
