### ISSUE TITLE
EQB 2.5 Profile: /codeBook/otherMat/citation/holdings/@URI

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#146]
**Original report on BitBucket by Darren Bell (GitHub: [darrenbell2](https://github.com/darrenbell2)).**

----------------------------------------

No need to use holdings, there otherMat/@&zwnj;URI

---

Source of comment:  
From: Katja Moilanen \(Basecamp\) [*email address removed*](mailto:*email address removed*)  
Sent: 30 November 2021 11:41  
To: Bell, Darren S [*email address removed*](mailto:*email address removed*)  
Subject: Re: \(CESSDA Metadata Office\) Your feedback on the new DDI profile drafts \(CDC and EQB\) is needed!  
please find attached to this message the FSD's feedback on the EQB DDI 2.5 profile.  It includes general comments about the profile as well as information about FSD's capability to produce "EQB valid" DDI 2.5 metadata.  
Best wishes,  
Katja

**Comment by katja-moilanen** [comment]
Quite likely, there is no need to use otherMat at all. The needed element is rather relPubl that is used for documenting publications in DDI-C. All otherMat elements needs to be removed.

**Comment by katja-moilanen** [comment]
This issues concerns old, deprecated EQB 2.5 profile.
