### ISSUE TITLE
CDC 2.5 Monolingual Profile /codebook/@xml:lang

### ISSUE THREAD

**Issue by MortenSikt** [cessda/cessda.metadata.profiles#149]
Update the requirements for the attribute from mandatory to recommended in order to ease admission of records provided by dataverse.

```
<!--ROOT ELEMENT-->
<pr:Used xpath="/codeBook/@xml:lang" isRequired="true">
...
<r:Content>Required: Mandatory</r:Content>
...
```

Edits should be:

```
<!--ROOT ELEMENT-->
<pr:Used xpath="/codeBook/@xml:lang" isRequired="false">
...
<r:Content>Required: Recommended</r:Content>
```

**Comment by darrenbell2** [comment]
/codeBook/xml:lang or /codeBook/xml-lang now Recommended (rather than Mandatory) in all CDC profiles.

**Comment by darrenbell2** [comment]
Have also now made @xsi:schemaLocation Recommended rather than Mandatory in all profiles, as this has caused issues for some SPs.

**Comment by matthew-morris-cessda** [comment]
This isn't merged yet, so reopening
