### ISSUE TITLE
CDC DDI-C (multilingual): dates and languages (collDate, distDate)

### ISSUE THREAD

**Issue by katja-moilanen** [cessda/cessda.metadata.profiles#172]
```
   <r:Content>Required: Mandatory if 'collDate' element is populated with a freetext
                expression.</r:Content>
```
but
```
<r:Content>
                <![CDATA[
                <Constraints>
                    <MandatoryNodeIfParentPresentConstraint/>
                </Constraints>
                ]]>
            </r:Content>
```

**Comment by katja-moilanen** [comment]
If collDate has information only in the date attribute, then there is no need for language tag at all.

Apparently CDC has some difficulties with showing elements without language information. Needs discussion with SO and developers.

**Comment by MortenSikt** [comment]
Is it not the case that the mandatory requirement always will kick in since the parent element needs to exist for the date attribute to be placed within it. The validation does not care if its empty or if there is anything in it, it does not look at that as far as I know.

But it is kinda pointless to require a language tag for date information I agree

**Comment by katja-moilanen** [comment]
DDI2.5 and DDI2.6:
   <pr:Used xpath="/ddi:codeBook/ddi:stdyDscr/ddi:stdyInfo/ddi:sumDscr/ddi:collDate/@xml:lang" isRequired="false">
        <r:Description>
            <r:Content>Required: Optional</r:Content>
            <r:Content>ElementType: Attribute</r:Content>
            <r:Content>Usage: Language of the free text expression of the collection period.
                ISO 639-1 codes are strongly encouraged to be used.</r:Content>
            <r:Content>CMM_Mapping: 1.3.7.4.1</r:Content>
        </r:Description>
        <pr:Instructions>
            <r:Content>
                <![CDATA[
			<Constraints>
				<OptionalNodeConstraint/>
			</Constraints>
			]]>
            </r:Content>
        </pr:Instructions>
    </pr:Used>
AND
    <pr:Used xpath="/ddi:codeBook/ddi:stdyDscr/ddi:citation/ddi:distStmt/ddi:distDate/@xml:lang" isRequired="false">
        <r:Description>
            <r:Content>Required: Optional</r:Content>
            <r:Content>ElementType: Attribute</r:Content>
            <r:Content>Usage: Language of the free text expression of the study description publication time.
                ISO 639-1 codes are strongly encouraged to be used.</r:Content>
            <r:Content>CMM_Mapping: None</r:Content>
        </r:Description>
        <pr:Instructions>
            <r:Content>
                <![CDATA[
			<Constraints>
				<OptionalNodeConstraint/>
			</Constraints>
			]]>
            </r:Content>
        </pr:Instructions>
    </pr:Used>

**Comment by katja-moilanen** [comment]
DDI1.2.2
```
    <pr:Used xpath="/ddi:codeBook/stdyDscr/stdyInfo/sumDscr/collDate/@xml-lang" isRequired="false">
        <r:Description>
            <r:Content>Required: Optional</r:Content>
            <r:Content>ElementType: Attribute</r:Content>
            <r:Content>Usage: Language of the free text expression of the collection period.
                ISO 639-1 codes are strongly encouraged to be used.</r:Content>
            <r:Content>CMM_Mapping: 1.3.7.4.1</r:Content>
        </r:Description>
        <pr:Instructions>
            <r:Content>
                <![CDATA[
			<Constraints>
				<OptionalNodeConstraint/>
			</Constraints>
			]]>
            </r:Content>
        </pr:Instructions>
    </pr:Used>
```
