### ISSUE TITLE
2.5 CDC Profile - feedback and PID handling

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#39]
**Original report on BitBucket by Darren Bell (GitHub: [darrenbell2](https://github.com/darrenbell2)).**

----------------------------------------

Use of /codeBook/stdyDscr/citation/holdings and /codeBook/stdyDscr/citation/titlStmt/IDNo/@&zwnj;agency

‌

From: Katja Moilanen \(Basecamp\) \[[mailto:*email address removed*](mailto:*email address removed*)\]  
Sent: 14 April 2021 09:51  
To: Bell, Darren S [*email address removed*](mailto:*email address removed*)  
Subject: \(CESSDA Metadata Office\) Questions for SPs about fulfilling the DDI profile requirements for CDC  
Dear all,  
we \(FSD\) checked the latest DDI 2.5 profile for CDC. We are now pondering how to update all our 3200 metadata records \(and our OAI-PMH endpoint software Kuha2\) so we are now curious to know if the other SPs have the same problems.

1. We have holdings element only in /codeBook/docDscr/citation/holdings . Do you have holdings element in /codeBook/stdyDscr/citation/holdings as the profile says?
2. We have used the /codeBook/stdyDscr/citation/titlStmt/IDNo/@&zwnj;agency attribute for the name of the agency that admitted the PID/IDNo. The profile says that the value of the /codeBook/stdyDscr/citation/titlStmt/IDNo/@&zwnj;agency should be one from the vocabulary [https://vocabularies.cessda.eu/vocabulary/CessdaPersistentIdentifierTypes](https://vocabularies.cessda.eu/vocabulary/CessdaPersistentIdentifierTypes) i.e. ARK or DOI or Handle or URN, if the IDNo holds PID. Do you have a string "DOI" or "URN" or "Handle" or  "ARK" in your agency attribute?

Best Regards,  
Katja Moilanen \(FSD\)

---

From: Benjamin Peuch \(Basecamp\) \[[mailto:*email address removed*](mailto:*email address removed*)\]  
Sent: 14 April 2021 10:02  
To: Bell, Darren S [*email address removed*](mailto:*email address removed*)  
Subject: Re: \(CESSDA Metadata Office\) Questions for SPs about fulfilling the DDI profile requirements for CDC

Hello Katja,

Here in Belgium we use Dataverse \(version 4.20; we plan to update to 5.4 asap\).

Dataverse indeed records a dataset's PID in two <IDNo> elements, one in <docDscr>, the other in <stdyDscr>, and both elements have an agency attribute whose value is either "DOI" or "Handle" depending on which PID was chosen upon installation.

However, Dataverse does not use the <holdings> element, which is why one of our developers wrote a script to enrich our DDI outputs and make them CDC-compliant. They now include such an element with the following syntax:

<holdings URI="[https://doi.org/10.34934/DVN/MHN9RA"/](https://doi.org/10.34934/DVN/MHN9RA%22/)>

We plan to share this script with the CESSDA community once it is fully tested and documented \(which should be soon\).

Cheers,  
Benjamin

**Comment by katja-moilanen** [comment]
This issue is no longer "up-to-date"
