### ISSUE TITLE
Link the profiles to the XSLT stylesheets.

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#62]
**Original report on BitBucket by Matthew Morris (GitHub: [matthew-morris-cessda](https://github.com/matthew-morris-cessda)).**

----------------------------------------

This presents a friendly view of the metadata profiles for users navigating to them using web browsers

**Comment by matthew-morris-cessda** [comment]
See https://cmv.cessda.eu/documentation/profiles.html
