### ISSUE TITLE
CDC 3.2 profile : consider using PublisherReference

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#67]
**Original report on BitBucket by Katja Moilanen.**

----------------------------------------

CDC 3.2 uses PublisherName, would it be better to use PublisherReference? By using PublisherReference \(and referencing to organization\), there would be a possibility to have an abbreviation for Publisher because Organization has  a feature Abbreviation \(//a:Organization/a:OrganizationIdentification/a:OrganizationName/r:Abbreviation\)

**Comment by darrenbell2** [comment]
Updated 3.2 profile to use r:PublisherReference/***
Committed to mdo-d6 branch
