### ISSUE TITLE
CDC 3.2 profile : consider using CreatorReference

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#68]
**Original report on BitBucket by Katja Moilanen.**

----------------------------------------

CDC DDI3.2 uses CreatorName, could the CreatorReference \(\+ other fields required\) be used instead?

**Comment by darrenbell2** [comment]
Updated 3.2 profile to use r:PublisherReference/***
Committed to mdo-d6 branch
