### ISSUE TITLE
CDC 3.2 profile : "required" column of the language of some descriptive terms

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#70]
**Original report on BitBucket by Katja Moilanen.**

----------------------------------------

“required” column texts like “Mandatory if ‘TypeofTimeMethod' element is present” should probably be changed to  “Mandatory if 'Content’ element is present”. Content element \(descriptive term\) is not mandatory e.g. for the TimeMethod/SamplingProcedure/ModeOfCollection and it is not a child of the TypeOfTimeMethod/TypeOfSamplingProcedure/TypeOfModeOfCollection.

**Comment by darrenbell2** [comment]
Checked all instances of "Mandatory if..." and made 3 updates in 3.2 profule:  

1.<r:Content>Required: Mandatory if '.../d:TimeMethod/r:Description/r:Content' element is present</r:Content>

2.<r:Content>Required: Mandatory if '.../d:SamplingProcedure/r:Description/r:Content' element is
                present</r:Content>

3.<r:Content>Required: Mandatory if '.../d:ModeOfCollection/r:Description/r:Content' element is
                present</r:Content>

**Comment by darrenbell2** [comment]
Committed to branch mdo-d6

**Comment by matthew-morris-cessda** [comment]
Reopening, as this hasn't been merged into main (or mdo-d6)
