### ISSUE TITLE
CDC 3.2 profile : Repeatibility of descriptive vocabulary terms

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#72]
**Original report on BitBucket by Katja Moilanen.**

----------------------------------------

This might be that we did not understand the structure of the profile correctly, but if the content field is repeatable, does it not mean that one controlled “code value” could have 0-n descriptive terms? Could it rather be that /ddi:DDIInstance/s:StudyUnit/d:DataCollection/d:CollectionEvent/d:ModeofCollection would be repeatable?

‌

**Comment by darrenbell2** [comment]
No - "repeatability" means that there can be multiple instances across the entire XML document.  It's not intended to indicate the repeatability within a particular child structure. This probably has not been made clear before.
