### ISSUE TITLE
EQB 2.5 Profile : Drop codeBook/@xml:lang?

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#82]
**Original report on BitBucket by Katja Moilanen.**

----------------------------------------

Each element that may have language has it already as attribute.

**Comment by katja-moilanen** [comment]
https://github.com/cessda/cessda.metadata.profiles/issues/112

**Comment by katja-moilanen** [comment]
This issues concerns old, deprecated EQB 2.5 profile.
