### ISSUE TITLE
EQB 2.5 Profile : Find a new XPath ( DDI 2.5 field) for metadata access?

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#83]
**Original report on BitBucket by Katja Moilanen.**

----------------------------------------

/codeBook/stdyDscr/citation/prodStmt/copyright and /codeBook/stdyDscr/dataAccs/useStmt/specPerm are used as metadata access conditions. The information about metadata should be in docDscr section.

/codeBook/stdyDscr/othrStdyMat/relMat/citation/prodStmt/copyright is used for question-related metadata access. docDscr or dataDscr better?

**Comment by katja-moilanen** [comment]
This issues concerns old, deprecated EQB 2.5 profile.
