### ISSUE TITLE
EQB 2.5 Profile : Name of the research instrument to otherMat

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#84]
**Original report on BitBucket by Katja Moilanen.**

----------------------------------------

resInstru is for the type of the research instrument. If the research instrument is described as a document then otherMat element is correct e.g. //otherMat/labl or //otherMat/citation/titlStmt/titl

Definition text is about language “The language of the instrument name that is being used in the study. ISO 639-1 codes are strongly encouraged to be used” and needs to be amended in any case.

**Comment by katja-moilanen** [comment]
XPath needs to be changed into codeBook/otherMat/citation/titlStmt/titl

**Comment by katja-moilanen** [comment]
This issues concerns old, deprecated EQB 2.5 profile.
