### ISSUE TITLE
EQB 2.5 Profile : use otherMat to document show cards not relMat

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#85]
**Original report on BitBucket by Katja Moilanen.**

----------------------------------------

According to DDI2.5 Specification otherMat is to be used for documenting show cards [https://ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/field\_level\_documentation\_files/schemas/codebook\_xsd/elements/otherMat.html](https://ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/field_level_documentation_files/schemas/codebook_xsd/elements/otherMat.html)

**Comment by katja-moilanen** [comment]
This field is not part of the EQB plans. Might need to be removed from the profile.

**Comment by katja-moilanen** [comment]
This issues concerns old, deprecated EQB 2.5 profile.
