### ISSUE TITLE
EQB 2.5 Profile : incorrect DDI2.5 XPath?

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#86]
**Original report on BitBucket by Katja Moilanen.**

----------------------------------------

/codeBook/dataDscr/var/location/@&zwnj;width is mostly used for the instructions “how to read data into statistical program” 

DDI2.5 specification says that this attribute "width" is number of columns the variable occupies.

‌
According to DDI-C specification, this element + attribute is not about the minimum length of the text variable, instead it is meant to assist in reading the variable from the file to a (statistical) programme. https://ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/field_level_documentation_files/schemas/codebook_xsd/elements/location.html

‌

**Comment by katja-moilanen** [comment]
This field is not part of the EQB plans. Might need to be removed from the profile.

**Comment by katja-moilanen** [comment]
This issues concerns old, deprecated EQB 2.5 profile.
