### ISSUE TITLE
EQB 2.5 Profile : Value of "Required" column differs from CMM and EQB DDI-L

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#87]
**Original report on BitBucket by Katja Moilanen.**

----------------------------------------
/codeBook/stdyDscr/citation/serStmt/serName
/codeBook/dataDscr/var/catgryGrp/@levelno
/codeBook/dataDscr/var/qstn/@elementVersion
/codeBook/dataDscr/var/@representationType
/codeBook/dataDscr/var/@nature
/codeBook/dataDscr/var/@missing
 /codeBook/dataDscr/var/@qstn

‌

**Comment by katja-moilanen** [comment]
https://github.com/cessda/cessda.metadata.profiles/issues/139
https://github.com/cessda/cessda.metadata.profiles/issues/129
https://github.com/cessda/cessda.metadata.profiles/issues/126
https://github.com/cessda/cessda.metadata.profiles/issues/99
https://github.com/cessda/cessda.metadata.profiles/issues/125
https://github.com/cessda/cessda.metadata.profiles/issues/95
