### ISSUE TITLE
EQB 2.5 Profile : XPath is incorrect, typo

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#88]
**Original report on BitBucket by Katja Moilanen.**

----------------------------------------

/codeBook/dataDscr/var/qstn/@&zwnj;IDNo is not a valid XPath but /codeBook/dataDscr/var/qstn/@&zwnj;ID is.

**Comment by katja-moilanen** [comment]
This field is not part of the EQB plans. Might need to be removed from the profile.

If needed change to //var/qstn/@id

**Comment by katja-moilanen** [comment]
This issues concerns old, deprecated EQB 2.5 profile.
