### ISSUE TITLE
EQB 2.5 Profile : //qstn/ExtLink

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#89]
**Original report on BitBucket by Katja Moilanen.**

----------------------------------------

Could //qstn/ @&zwnj;ID to be used instead? If not, needs to noted that URI is mandatory attribute for ExtLink.

**Comment by katja-moilanen** [comment]
This field is not part of the EQB plans. Might need to be removed from the profile.

**Comment by katja-moilanen** [comment]
This issues concerns old, deprecated EQB 2.5 profile.
