### ISSUE TITLE
EQB 2.5 Profile : possibility to avoid list element

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#90]
**Original report on BitBucket by Katja Moilanen.**

----------------------------------------

Question label could be put directly into //qstn \(its type is mixed\) then there would not be need to use list element.

**Comment by katja-moilanen** [comment]
This field is not part of the EQB plans. Might need to be removed from the profile.

**Comment by katja-moilanen** [comment]
This issues concerns old, deprecated EQB 2.5 profile.
