### ISSUE TITLE
EQB 2.5 Profile : Two Question number fields

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#91]
**Original report on BitBucket by Katja Moilanen.**

----------------------------------------

/codeBook/dataDscr/var/qstn/@&zwnj;seqNo and /codeBook/dataDscr/var/qstn/list/itm have definitions that tells that they both are for question number. If they are exactly the same field, delete other one. If not, amend the definition so the it is easier to understand the difference between these two.

**Comment by katja-moilanen** [comment]
These fields are not part of the EQB plans. Might need to be removed from the profile.

**Comment by katja-moilanen** [comment]
This issues concerns old, deprecated EQB 2.5 profile.
