### ISSUE TITLE
EQB 2.5 Profile : there is postQTxt for postquestion texts in DDI-C

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#92]
**Original report on BitBucket by Katja Moilanen.**

----------------------------------------

preQTxt should not be used for postquestion texts.

**Comment by katja-moilanen** [comment]
Add as optional:
/codeBook/dataDscr/var/qstn/postQTxt
And also:
/codeBook/dataDscr/var/qstn/forward
/codeBook/dataDscr/var/qstn/backward
Then all there are all the statement items needed for EQB plans.

**Comment by katja-moilanen** [comment]
This issues concerns old, deprecated EQB 2.5 profile.
