### ISSUE TITLE
EQB 2.5 Profile : Is there more suitable XPath in DDI-C?

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#93]
**Original report on BitBucket by Katja Moilanen.**

----------------------------------------

using /codeBook/dataDscr/var/concept/list

/codeBook/dataDscr/var/concept/list/itm

/codeBook/dataDscr/var/qstn/list/label \(suggestion, use only qstn\)

/codeBook/dataDscr/var/qstn/list/itm

/codeBook/dataDscr/var/@&zwnj;xml:lang \(Drop this?\)

**Comment by katja-moilanen** [comment]
https://github.com/cessda/cessda.metadata.profiles/issues/144
https://github.com/cessda/cessda.metadata.profiles/issues/90
https://github.com/cessda/cessda.metadata.profiles/issues/91
