### ISSUE TITLE
EQB 2.5 Profile: Elements / attributes that seems to be missing

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#94]
**Original report on BitBucket by Katja Moilanen.**

----------------------------------------

if there is text in collDate then there is need for attribute xml:lang \(//collDate/@&zwnj;xml:lang\)

Missing qstn and if qstn is O/R/M, many attributes of /codeBook/dataDscr/var/qstn are "mandatory if qstn is present"  
Missing range and if range is O/R/M, attributes of /codeBook/dataDscr/var/valrng/range are "mandatory if range is present"  
Missing catgryGrp and if catgryGrp is O/R/M, attributes of /codeBook/dataDscr/var/catgryGrp/ are "mandatory if catgryGrp is present"  
Missing catgryGrp/labl and if labl is O/R/M, attributes of /codeBook/dataDscr/var/catgryGrp/labl are "mandatory if catgryGrp/labl is present"  
Missing catgry and if catgry is O/R/M, attributes of /codeBook/dataDscr/var/catgry/ are "mandatory if catgry is present"  
Variable groups could be used for question grids, but they are missing from the DDI-C profile  
Language of the instrument

‌

**Comment by katja-moilanen** [comment]
This issues concerns old, deprecated EQB 2.5 profile.
