### ISSUE TITLE
EQB 2.5 Profile:  /codeBook/dataDscr/var/@qstn

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.metadata.profiles#99]
**Original report on BitBucket by Darren Bell (GitHub: [darrenbell2](https://github.com/darrenbell2)).**

----------------------------------------

From Olof Olsson 01-Nov-21.  Basecamp Message ID: [https://3.basecamp.com/3584575/buckets/1716357/messages/4282415300#\_\_recording\_4306736571](https://3.basecamp.com/3584575/buckets/1716357/messages/4282415300#__recording_4306736571)

[https://cmv.cessda.eu/profiles/eqb/ddi-2.5/0.1.0/profile.xml](https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fcmv.cessda.eu%2fprofiles%2feqb%2fddi-2.5%2f0.1.0%2fprofile.xml&c=E,1,5FCxV1gmJ-GOmGgbFVMkeNhuKFgaSchwFCmAtq7HUXENV53-HpRkHs5kJR0bq03PcFBSULFShPFFfwALIeulhEviP8hySHAVX9aCfW6G6QPzVnxrOg,,&typo=1)  
**/codeBook/dataDscr/var/@&zwnj;qstn**   
Should be optional, not all variables have a related question

**Comment by katja-moilanen** [comment]
This issues concerns old, deprecated EQB 2.5 profile.
